api_platform:
  title: Hello API Platform
  version: 1.0.0
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  defaults:
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
  exception_to_status:
    App\Exception\InvalidParameterException: 400
  enable_docs: true
